const roles = [
  { role: 'Django developer', featured: true },
  { role: 'React advocate', featured: true },
  { role: 'SASS enthusiast', featured: true },
  { role: 'SMACSS guru', featured: true },
  { role: 'Python programmer', featured: true },
  { role: 'Guitar mangler', featured: false },
  { role: 'Reader of books', featured: false },
  { role: 'Vexillologist', featured: false },
  { role: 'Pun-lover', featured: false },
  { role: 'Icelander', featured: false },
  { role: 'Descendant of Flemish Counts', featured: false },
  { role: 'Gentenaar', featured: false },
  { role: 'Akureyringur', featured: false },
  { role: 'Semi-Italian', featured: false },
  { role: 'Gourmand', featured: false },
  { role: 'Homebrewer', featured: false },
  { role: 'Rubik\'s Cube solver', featured: false },
  { role: 'Mac user', featured: false },
  { role: 'Linux hacker', featured: false },
  { role: 'Cartography lover', featured: false },
  { role: 'Music listener', featured: false },
  { role: 'Father of two', featured: false },
];

export default roles;
